esd:
  profiles:
    active: local
  server:
    name: demo
    worker_num: 1
    max_conn: 1024
    debug: true
  port:
    http:
      host: 0.0.0.0
      port: 8081
      open_http_protocol: true
      sock_type: 1
    ws:
      host: 0.0.0.0
      port: 8082
      open_websocket_protocol: true
      sock_type: 1

tracing:
  host: my-jaeger-agent.jaeger-operator.svc.cluster.local